name: Python Lint and Train Check

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest
      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
      - name: Check Python syntax
        run: |
          python -m py_compile $(git ls-files '*.py')
      - name: Run tests
        run: |
          PYTEST_DISABLE_PLUGIN_AUTOLOAD=1 pytest -ra
      - name: Dry-run training
        run: |
          python train_caption.py --dry-run
